In [20]:
import pandas as pd
import numpy as np

In [21]:
data = pd.read_excel("multiple_linear_regression.xlsx")
data.head(5)

                  Name  Age  Experience (Years)  Education (Years)    Salary
0  Mr. Johnathan Davis   56                   8                 15  14372.40
1           Kelly Reed   46                   7                 10  12641.59
2        Chelsea Moore   32                  11                 18  13918.89
3        Paige Goodwin   25                  33                 15  16396.54
4        Kelly Rosario   38                  32                 12  15350.48

In [22]:
data.isnull().sum()

Name                  0
Age                   0
Experience (Years)    0
Education (Years)     0
Salary                0
dtype: int64

In [23]:
data.duplicated().sum()

np.int64(0)

In [24]:
data.dropna().sum()

Name                  Mr. Johnathan DavisKelly ReedChelsea MoorePaig...
Age                                                                3791
Experience (Years)                                                 2041
Education (Years)                                                  1386
Salary                                                       1412565.47
dtype: object

In [25]:
data.drop(columns=["Name"], inplace=True)

In [41]:
x = data.iloc[:,:-1]
y = data["Salary"]

In [42]:
from sklearn.preprocessing import StandardScaler

In [47]:
ss = StandardScaler()
df = ss.fit(data)

In [48]:
database= pd.DataFrame(ss.transform(data))

In [39]:
database

           0         1         2         3
0   1.487884 -0.989475  0.412968  0.080398
1   0.665394 -1.069207 -1.398294 -0.483559
2  -0.486092 -0.750279  1.499724 -0.067371
3  -1.061835  1.003827  0.412968  0.739932
4   0.007402  0.924095 -0.673789  0.399090
..       ...       ...       ...       ...
95  1.734631  1.322755 -1.398294  1.436254
96  1.487884  0.206506  0.050715  0.727062
97  1.652382 -1.308403  0.412968  0.391267
98  0.583145  1.003827 -0.673789  1.261955
99 -1.144084 -1.228671  1.499724 -1.565434

[100 rows x 4 columns]

In [54]:
x = database.iloc[:,:-1]
y = database[3]

In [56]:
x

           0         1         2
0   1.487884 -0.989475  0.412968
1   0.665394 -1.069207 -1.398294
2  -0.486092 -0.750279  1.499724
3  -1.061835  1.003827  0.412968
4   0.007402  0.924095 -0.673789
..       ...       ...       ...
95  1.734631  1.322755 -1.398294
96  1.487884  0.206506  0.050715
97  1.652382 -1.308403  0.412968
98  0.583145  1.003827 -0.673789
99 -1.144084 -1.228671  1.499724

[100 rows x 3 columns]

In [57]:
from sklearn.linear_model import LinearRegression

In [63]:
lr = LinearRegression()
lr.fit(x,y)

LinearRegression()

In [ ]:
lr.score(x,y)*100

87.99469598469304